"""
ListingGapAnalyzer — scores a product listing against a category-specific buyer checklist.

Takes the 5-question checklist generated by ProductIntelligence and determines for each
question whether the listing text ANSWERS it, PARTIALLY answers it, or MISSES it entirely.

This grounds every panel persona reaction in specific, identifiable gaps rather than
free-form opinions — preventing hallucination and focusing feedback on actionable issues.

The formatted gap context is injected into every agent prompt so personas react to
REAL gaps in THIS listing, not invented generic concerns.
"""

import json
import logging
import re
from dataclasses import dataclass
from typing import List

logger = logging.getLogger("miroshop.gap_analyzer")


GAP_ANALYSIS_PROMPT = """You are auditing a product listing to identify information gaps that real buyers care about.

Product listing text:
---
{listing_text}
---

For each buyer question below, determine if the listing ANSWERS it, PARTIALLY answers it, or MISSES it entirely.

Buyer questions:
{checklist_text}

Scoring rules:
- ANSWERED: The listing directly and clearly answers this question with specific information.
- PARTIAL: The listing hints at this but leaves a key part unanswered — a buyer would still wonder.
- MISSING: The listing says nothing about this. A buyer would have to guess or contact the store.

For evidence: quote the exact relevant phrase from the listing (max 80 chars), or write "(not found)" if missing.

Respond with ONLY valid JSON, no markdown:
{{
  "gaps": [
    {{"question": "exact question text", "status": "ANSWERED", "evidence": "relevant quote", "confidence": 0.9}},
    {{"question": "exact question text", "status": "PARTIAL", "evidence": "partial quote", "confidence": 0.7}},
    {{"question": "exact question text", "status": "MISSING", "evidence": "(not found)", "confidence": 0.8}}
  ]
}}"""


@dataclass
class GapItem:
    question: str
    status: str       # "ANSWERED" | "PARTIAL" | "MISSING"
    evidence: str     # Relevant quote or "(not found)"
    confidence: float # 0.0–1.0


@dataclass
class GapAnalysis:
    items: List[GapItem]

    @property
    def missing(self) -> List[GapItem]:
        return [i for i in self.items if i.status == "MISSING"]

    @property
    def partial(self) -> List[GapItem]:
        return [i for i in self.items if i.status == "PARTIAL"]

    @property
    def answered(self) -> List[GapItem]:
        return [i for i in self.items if i.status == "ANSWERED"]

    @property
    def has_gaps(self) -> bool:
        return bool(self.missing or self.partial)


def analyze_listing_gaps(
    llm,
    checklist: List[str],
    listing_text: str,
) -> "GapAnalysis | None":
    """
    Score each checklist item against the listing text.
    Returns None on failure — caller proceeds without gap analysis (graceful degradation).
    """
    if not checklist or not listing_text:
        return None

    import os as _os
    if _os.environ.get("SKIP_ARCHETYPE_GEN") == "1":
        return None

    checklist_text = "\n".join(f"{i + 1}. {q}" for i, q in enumerate(checklist))
    listing_excerpt = listing_text[:2000]  # Keep within token budget

    prompt = GAP_ANALYSIS_PROMPT.format(
        listing_text=listing_excerpt,
        checklist_text=checklist_text,
    )

    try:
        raw = llm.chat(
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,   # Near-deterministic — same listing should give same gaps
            max_tokens=700,
        )
        if not raw or not raw.strip():
            raise ValueError("Empty response")

        cleaned = raw.strip()
        cleaned = re.sub(r'^```(?:json)?\s*\n?', '', cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r'\n?```\s*$', '', cleaned)

        data = json.loads(cleaned.strip())
        gaps_raw = data.get("gaps", [])

        items: List[GapItem] = []
        for g in gaps_raw:
            status = str(g.get("status", "MISSING")).upper()
            if status not in ("ANSWERED", "PARTIAL", "MISSING"):
                status = "MISSING"
            items.append(GapItem(
                question=str(g.get("question", ""))[:200],
                status=status,
                evidence=str(g.get("evidence", "(not found)"))[:120],
                confidence=float(g.get("confidence", 0.5)),
            ))

        if not items:
            return None

        answered_count = sum(1 for i in items if i.status == "ANSWERED")
        partial_count = sum(1 for i in items if i.status == "PARTIAL")
        missing_count = sum(1 for i in items if i.status == "MISSING")
        logger.info(
            f"Gap analysis complete: {answered_count} answered, "
            f"{partial_count} partial, {missing_count} missing"
        )
        return GapAnalysis(items=items)

    except Exception as e:
        logger.warning(f"Gap analysis failed: {e}. Panel will evaluate without gap context.")
        return None


def format_gap_context(gap_analysis: "GapAnalysis | None") -> str:
    """
    Format gap analysis results into the {gap_context} block injected into every agent prompt.

    Only surfaces actionable gaps (MISSING/PARTIAL) so personas react to real evidence.
    Returns empty string if gap_analysis is None (graceful degradation).
    """
    if gap_analysis is None:
        return ""

    lines = ["LISTING GAP ANALYSIS — base your concerns on these findings only:"]

    answered = gap_analysis.answered
    partial = gap_analysis.partial
    missing = gap_analysis.missing

    if answered:
        lines.append("Confirmed in listing (do NOT flag these as missing):")
        for item in answered:
            lines.append(f"  ✓ {item.question}")
            if item.evidence and item.evidence != "(not found)":
                lines.append(f"    → \"{item.evidence}\"")

    if partial:
        lines.append("Partially addressed (valid concern — buyer would still wonder):")
        for item in partial:
            lines.append(f"  ~ {item.question}")
            if item.evidence and item.evidence != "(not found)":
                lines.append(f"    → partially: \"{item.evidence}\"")

    if missing:
        lines.append("Not addressed in listing (legitimate gaps a buyer would notice):")
        for item in missing:
            lines.append(f"  ✗ {item.question}")

    if not (partial or missing):
        lines.append("This listing answers all key buyer questions well.")

    lines.append(
        "\nIMPORTANT: Your concerns MUST come from the gaps listed above. "
        "Do not invent concerns not in this analysis. "
        "Each panelist should focus on the gap most relevant to their personal priorities."
    )

    return "\n".join(lines)
